### ISSUE TITLE
支持二级目录

### ISSUE THREAD

**Issue by gaocegege** [siglt/tosknight#15]
腾讯系的服务条款可以归在一个 category 下

对 yaml 可能需要做一些改动:

```
webs:
  - name: 腾讯
    items:
      - xxxx
```
